development:
  adapter: redis
  url: redis://localhost:6379/1

test:
  adapter: test

roduction:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: senpai_api_staginv


production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: senpai_api_production
